export const portfolios = [
    {
        id: 1,
        category: 'Reactjs',
        image: './assets/img1.jpg',
        github: 'http://www.github.com/narendram224',
        linkedin: 'http://www.linkedin.com/narendram224',
        title: 'How to get Data form React',
        text: 'Num of programming languages',
    },
    {
        id: 2,
        category: 'Docker',
        image: './assets/img1.jpg',
        github: 'http://www.github.com/narendram224',
        linkedin: 'http://www.linkedin.com/narendram224',
        title: 'How to sfsfsfsf React',
        text: 'Num of programming languages',
    },
    {
        id: 3,
        category: 'Nodejs',
        image: './assets/img1.jpg',
        github: 'http://www.github.com/narendram224',
        linkedin: 'http://www.linkedin.com/narendram224',
        title: 'How to use React',
        text: 'Num of programming languages',
    },
    {
        id: 4,
        category: 'Express',
        image: './assets/img1.jpg',
        github: 'http://www.github.com/narendram224',
        linkedin: 'http://www.linkedin.com/narendram224',
        title: 'How to use React',
        text: 'Num of programming languages',
    },
    {
        id: 5,
        category: 'Reactjs',
        image: './assets/img1.jpg',
        github: 'http://www.github.com/narendram224',
        linkedin: 'http://www.linkedin.com/narendram224',
        title: 'How to use React',
        text: 'Num of programming languages',
    },
]
